version: '3.7'

volumes:
  static:

services: 
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    ports:
      - '9000:9000'
      - '39000:39000'
    volumes:
      - .:/app
      - /app/vendor
      - static:/static
    depends_on:
      - mariadb

  frontend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: frontend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/templates/skin/synio/locale/ru_RU/LC_MESSAGES
      - static:/app/static
    command: npm run build-dev

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - .:/app
      - static:/app/static
    depends_on: 
      - php-fpm

  mariadb:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile

  redis:
    image: redis:alpine
